package pt.pak3nuh.hollywood.processor

@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
/**
 * Indicates the class was generated by an automatic tool.
 * @param timestamp The time of the generation round.
 */
annotation class Generated(val timestamp: String)
