# https://github.com/marketplace/actions/gradle-command
name: CI

on: [push]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: eskatos/gradle-command-action@v1
        timeout-minutes: 10
        with:
          arguments: build
